# Generated by Django 4.1.3 on 2022-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('item_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('avg_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('total_quantity', models.IntegerField()),
            ],
            options={
                'unique_together': {('item_id', 'date')},
            },
        ),
    ]
