# Generated by Django 4.1.3 on 2022-12-21 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('year_released', models.IntegerField()),
                ('item_type', models.CharField(choices=[('M', 'minifig'), ('S', 'set')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_path', models.CharField(max_length=140)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.item')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_record', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='%d-%m-%Y')),
                ('avg_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('total_quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.item')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('U', 'used'), ('N', 'new')], max_length=1)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
    ]
