# Generated by Django 4.1.3 on 2023-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateField(blank=True, default='1999-01-01', null=True, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_preference',
            field=models.CharField(choices=[('Never', 'Never'), ('Occasional', 'Occasional'), ('All', 'All')], default='All', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateField(blank=True, default='1999-01-01', null=True, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(blank=True, default='1999-01-01', null=True, verbose_name='YYYY-MM-DD'),
        ),
    ]
