# Generated by Django 4.1.3 on 2022-12-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='item_id',
            new_name='item',
        ),
    ]
