# Generated by Django 4.1.3 on 2023-01-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_portfolio_view_count_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateField(blank=True, default='1999-01-02', null=True, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(blank=True, default='1999-01-02', null=True, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(blank=True, default='1999-01-02', null=True, verbose_name='YYYY-MM-DD'),
        ),
    ]
