# Generated by Django 4.1.3 on 2022-12-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_item_id_price_item_rename_item_id_theme_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_added',
            field=models.DateField(blank=True, default='null', null=True, verbose_name='%d-%m-%Y'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.item'),
        ),
    ]
