# Generated by Django 4.1.3 on 2022-12-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_portfolio_date_added_alter_theme_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateField(default='null', verbose_name='%d-%m-%Y'),
        ),
    ]
